configs:
  nginx_site_config:
    file: ./nginx-conf/sites-available/gunicorn

services:
  postgres:
    image: postgres:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres -d netology_stocks_products"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - .:/docker-entrypoint-initdb.d
    env_file:
      - db.env

  backend:
    build: ./stocks_products
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    build: ./my_nginx
    ports:
      - "88:80"
    depends_on:
      - backend